
spring.datasource.url=jdbc:mysql://localhost:3306/donation_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8081

jwt.secret=donation_super_secret_key_123456789
jwt.expiration=86400000


admin.email=admin@donation.com
admin.password=Admin@1234

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=madhukaleru36@gmail.com
spring.mail.password=puarnbwkgahnlwnc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

this is my current application property

connection url:-mysql://root:FzHbBLcSPVMQauNUpRmBZipGMPWQTfUn@shortline.proxy.rlwy.net:44863/railway

password :- FzHbBLcSPVMQauNUpRmBZipGMPWQTfUn